name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        run: |
          apt-get update && apt-get install -y python3 python3-pip
          ln -s /usr/bin/python3 /usr/bin/python  # Ensure `python` points to `python3`
      - name: Set up virtual environment
        run: |
          python -m pip install --upgrade pip
          python -m pip install virtualenv
          virtualenv venv
          source venv/bin/activate
      - name: Train my model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          source venv/bin/activate
          pip install -r requirements.txt
          python model.py



