name: mlops-exaple-tensorflow-regression
on: [push]
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y python3-pip
      - name: Train my model
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pip install -r requirements.txt
          python model.py
